[package]
name = "site"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = { version = "2.2.0", features = ["js"] }
gloo = { version = "0.11.0", features = ["timers"] }
web-sys = { version = "0.3.74", features = ["Window"] }
yew = { version = "0.21.0", features = ["csr"] }
